window.UI_STRINGS = {
  error: "Error",
  registeredMaster: "registered master audio",
  registeredSongs: "registered songs.json",
  preparedVideo: "prepared video",
  ignored: "ignored",
  masterAudio: "Master audio",
  missingVideo: "Missing at least one video",
  missingMaster: "Missing master audio",
  noSongsContinuous: "No songs.json: I'll make one continuous video",
  ready: "Ready",
  noCompatibleFiles: "I couldn't find compatible files",
  prepareFailed: "I couldn't prepare the files",
  prepareTimeout: "Preparing took too long",
  working: "Working...",
  nextStep: "Calculating the next step...",
  elapsed: "Elapsed",
  eta: "ETA",
  calculating: "calculating...",
  doneTitle: "Your video is ready",
  failedTitle: "I couldn't finish the video",
  reportCopied: "Report copied",
  statusUpdateFailed: "I couldn't update progress",
  allSongs: "All",
  logs: "Open logs",
  reveal: "Show in Finder",
};
